theme: osuny
_merge: deep
services:
  rss:
    limit: 100
params:
  summary:
    position: hero

  # Design system
  logo:
    header: '/assets/images/logo.png'
    footer: '/assets/images/logo.png'
  # breadcrumb:
  #   extendable: false
  #   position: hero-start # hero-start | hero-end | after-hero | after-hero-title | none
  search:
    active: false
    positions:
      - primary
      # - upper-menu
      # - fixed
      # - footer
  home:
    head:
      title: site


  # BLOCKS
  blocks:
    image_sizes:
    _default:
      carousel:
        mobile:   360
        tablet:   555
        desktop:  575