theme: osuny
_merge: deep
services:
  rss:
    limit: 100

pagination:
  pagerSize: 36

params:
  summary:
    position: hero

  # Design system
  logo:
    header: '/assets/images/logo.png'
    footer: '/assets/images/logo.png'
  
  
  toc:                          # Table des matières (globale)
    force_offcanvas: false      # N'est pas forcée en panneau latéral hors-canvas
    disabled: false             # Activée par défaut
  
  # components:
  #   hero_image:
  #     in_hero:
  #       disabled: true

  search:
    active: true
    positions:
      - primary
      # - upper-menu
      # - fixed
      - footer

  share_links:
    enabled: true
    email: true
    facebook: true
    mastodon: true
    linkedin: true

  home:
    head:
      title: site

  # SECTIONS
  default:
    sitemap:
      ignore_children: false
    index:
      subtitle: false
      taxonomies:
        display: true
        layout: dropdown # dropdown | inline
        show_name: true
        
    single:
      taxonomies:
        position: content # content | hero | none
        layout: inline # dropdown | inline
        show_name: true

  pages:
    default_image: false
    index:
      layout: list # grid | list
      options:
        categories: false
        image: true
        main_summary: false
        subtitle: true
        summary: true
      truncate_description: 200 # Set to 0 to disable truncate
    single:
      taxonomies:
        position: hero # content | hero | none

  publications:
    index:
      group_by_year: true
    filters:
      anr: false

  categories:
    index:
      layout: grid # alternate | cards | grid | large | list
      options:
        image: true
        summary: true
    single:
      taxonomies:
        display: false

  projects:
    date_format: "2006"
    # default_image: false
    index:
      layout: grid # alternate | grid | large | list
      options:
        categories: true
        image: true
        subtitle: true
        summary: false
        year: true
      share_links: false
      truncate_description: 200 # Set to 0 to disable truncate
      navigation:
        reversed: false
  
  # Actualités    
  posts:
    index:
      archives: true
      layout: grid # grid | list
      options:
        author: true
        categories: true
        date: false
        image: true
        reading_time: false
        summary: false
        subtitle: true
      truncate_description: 200 # Set to 0 to disable truncate
    single:
      options:
        authors: true
        published_at: false
        reading_time: true
        signature: false
        updated_at: true
        image: false

  persons:
    index:
      taxonomies:
        display: false

  blocks:
    image_sizes:
      _default:
        hero:
          mobile:   400
          tablet:   800
          desktop:  750
        layouts:
          alternate:
            mobile:   360
            tablet:   555
            desktop:  520
          cards:
            mobile:   360
            tablet:   555
            desktop:  575
          carousel:
            mobile:   360
            tablet:   555
            desktop:  575
          grid:
            mobile:   360
            tablet:   555
            desktop:  575
        sections:
          projects:
            hero:
              mobile:   400
              tablet:   800
              desktop:  750
            hero_single:
              mobile:   400
              tablet:   800
              desktop:  750
