theme: osuny
_merge: deep

pagination:
  pagerSize: 12

params:
  # Design system
  logo:
    header: '/assets/images/logo.png'
    footer: '/assets/images/logo.png'
  # Fonction recherche
  search:
    active: true
    positions:
      - primary
  menu:
    primary:
      level_1:
        dropdown: true
        title:
          active: true
          source: "Summary" # "Summary" | "meta_description"
          truncate: 125
          summary:
            active: true

  share_links:
    enabled: true
    email: true
    mastodon: true

  categories:
    index:
      layout: grid
      options:
        image: true
        summary: true
    single:
      taxonomies:
        display: false
  # section PROJETS
  projects:
    date_format: "2006"
    index:
      layout: grid
      options:
        summary: false
        year: true
        #(???) ordre des projets par ordre chrono ? (ancien au + récent)
    single:
      share_links: false
      meta:
        position: hero
        options:
          reading_time: false
          with_labels: false
          year: false

  # section Actualités    
  posts: #(???) Pas possibe d'archive/tri par année 
    index:
      layout: list
      options:
        author: true
        summary: true
        subtitle: true
    single:
      meta:
        position: hero
        options:
          reading_time: false
          with_labels: false
      options:
        signature: false
  # section PERSONNES
  persons:
    index:
      taxonomies:
        display: false


  image_sizes:
      sections:
        projects:
          hero_single:
            mobile:   400
            tablet:   800
            desktop:  1600
        pages:
          layouts:
            grid:
              mobile:   700
              tablet:   1000
              desktop:  1500