[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/actualites-v01/film/ressource-par-film/nicole-nicole/index.html"
to = "/actualites-v01/film/nicole-nicole/"

[[redirects]]
from = "/personnes/alice-marsal/index.html"
to = "/coop/alice-marsal/"

[[redirects]]
from = "/personnes/romane-martin/index.html"
to = "/coop/romane-martin/"

[[redirects]]
from = "/actualites-v01/actus/actualites-des-films/nicole-nicole/index.html"
to = "/actualites-v01/film/nicole-nicole/"

[[redirects]]
from = "/actualites/type/actualite-des-films/index.html"
to = "/actualites/actus/actualites-des-films/"

[[redirects]]
from = "/personnes/clothilde-bunod/index.html"
to = "/coop/clothilde-bunod/"

[[redirects]]
from = "/agenda/2026/la-prochaine-permanence-aux-etats-generaux-du-documentaire-1/index.html"
to = "/agenda/2025/la-prochaine-permanence-aux-etats-generaux-du-documentaire-1/"

[[redirects]]
from = "/personnes/equipe-editoriale/index.html"
to = "/coop/equipe-editoriale/"

[[redirects]]
from = "/actualites/2026-05-19-lauren-dallenbach-dans-doc-session/index.html"
to = "/actualites-v01/2026-05-19-lauren-dallenbach-dans-doc-session/"

[[redirects]]
from = "/actualites/type/actualites-des-films/index.html"
to = "/actualites/actus/actualites-des-films/"

[[redirects]]
from = "/personnes/avrin-cardi/index.html"
to = "/coop/anne-cardi-avrin/"

[[redirects]]
from = "/actualites/2026-06-10-journal-de-cuisine/index.html"
to = "/actualites-v01/2026-06-10-journal-de-cuisine/"

[[redirects]]
from = "/personnes/categories/membres/index.html"
to = "/coop/categories/membres/"

[[redirects]]
from = "/coop/jean-charles-leyris/actualites/index.html"
to = "/coop/jean-charles-leyris/actualites-v01/"

[[redirects]]
from = "/personnes/sylvie-plunian/index.html"
to = "/coop/sylvie-plunian/"

[[redirects]]
from = "/personnes/jean-charles-leyris/index.html"
to = "/coop/jean-charles-leyris/"

[[redirects]]
from = "/personnes/categories/ancien-membre/index.html"
to = "/coop/categories/anciens-membres/"

[[redirects]]
from = "/personnes/categories/membre/index.html"
to = "/coop/categories/membres/"

[[redirects]]
from = "/actualites/2026-05-19-sed-a-neque-non-nulla-consectetur-tincidunt/index.html"
to = "/actualites-v01/2026-05-19-sed-a-neque-non-nulla-consectetur-tincidunt/"

[[redirects]]
from = "/tenk/index.html"
to = "/organisations/tenk/"

[[redirects]]
from = "/personnes/chantal-tran/index.html"
to = "/coop/chantal-tran/"

[[redirects]]
from = "/personnes/flora-jouvencel/index.html"
to = "/coop/flora-jouvencel/"

[[redirects]]
from = "/archives-expositions/index.html"
to = "/expositions/archives-expositions/"

[[redirects]]
from = "/ressources/lauren-dallenbach-dans-doc-session-1/index.html"
to = "/ressources-v01/lauren-dallenbach-dans-doc-session-1/"

[[redirects]]
from = "/actualites/ressources-1/index.html"
to = "/actualites-v01/ressources/"

[[redirects]]
from = "/actualites/2026-05-20-prix-dnicole-nicole-remporte-le-prix-du-jury-a-visions-du-reel/index.html"
to = "/actualites-v01/2026-05-20-prix-dnicole-nicole-remporte-le-prix-du-jury-a-visions-du-reel/"

[[redirects]]
from = "/actualites/ressources-1/la-vie-des-producteurs/index.html"
to = "/actualites-v01/ressources/la-vie-des-producteurs/"

[[redirects]]
from = "/personnes/categories/anciens-membres/index.html"
to = "/coop/categories/anciens-membres/"

[[redirects]]
from = "/personnes/raphaele-dumas/index.html"
to = "/coop/raphaele-dumas/"

[[redirects]]
from = "/actualites-v01/actus/index.html"
to = "/actualites/actus/"

[[redirects]]
from = "/personnes/claire-marty/index.html"
to = "/coop/claire-marty/"

[[redirects]]
from = "/films/2026-nicole-nicole-1/index.html"
to = "/films/2026-nicolenicole/"

[[redirects]]
from = "/actualites/2023-05-20-prix-du-jury-a-visions-du-reel-pour-nicole-nicole-1-1/index.html"
to = "/actualites/2020-06-02-prix-du-jury-a-visions-du-reel-pour-nicole-nicole-1-1/"

[[redirects]]
from = "/actualites-v01/index.html"
to = "/actualites/"

[[redirects]]
from = "/actualites/2026-05-20-prix-du-jury-a-visions-du-reel-pour-nicole-nicole-1/index.html"
to = "/actualites-v01/2026-05-20-prix-dnicole-nicole-remporte-le-prix-du-jury-a-visions-du-reel/"

[[redirects]]
from = "/actualites/type/actualites-de-la-scic/index.html"
to = "/actualites/actus/actualites-de-la-scic/"

[[redirects]]
from = "/personnes/aurelia-pfend/index.html"
to = "/coop/aurelia-pfend/"

[[redirects]]
from = "/actualites/type/index.html"
to = "/actualites/actus/"

[[redirects]]
from = "/projets/en-developpement/index.html"
to = "/films/statut/en-developpement/"

[[redirects]]
from = "/actualites/film/nicole-nicole/index.html"
to = "/actualites-v01/film/nicole-nicole/"

[[redirects]]
from = "/categories/diffuseur/index.html"
to = "/organisations/categories/diffuseur/"

[[redirects]]
from = "/actualites/2026-05-20-prix-du-jury-a-visions-du-reel-pour-nicole-nicole-1-1/index.html"
to = "/actualites/2020-06-02-prix-du-jury-a-visions-du-reel-pour-nicole-nicole-1-1/"

[[redirects]]
from = "/projets/en-diffusion/index.html"
to = "/films/statut/en-diffusion/"

[[redirects]]
from = "/actualites/2026-05-19-prix-du-jury-a-visions-du-reel-pour-nicole-nicole/index.html"
to = "/actualites-v01/2026-05-19-sed-a-neque-non-nulla-consectetur-tincidunt/"

[[redirects]]
from = "/actualites-v01/actus/actualites-des-films/4801-nuits/index.html"
to = "/actualites-v01/film/4801-nuits/"

[[redirects]]
from = "/personnes/index.html"
to = "/coop/"

[[redirects]]
from = "/actualites/type/actualites-du-site/index.html"
to = "/actualites/actus/actualites-du-site/"

[[redirects]]
from = "/actualites/par-film/nicole-nicole/index.html"
to = "/actualites-v01/film/nicole-nicole/"

[[redirects]]
from = "/ressources/lauren-dallenbach-dans-doc-session/index.html"
to = "/ressources-v01/lauren-dallenbach-dans-doc-session/"

[[redirects]]
from = "/films/2026-les-cedres-1/index.html"
to = "/films/2026-nei/"

[[redirects]]
from = "/coop/avrin-cardi/index.html"
to = "/coop/anne-cardi-avrin/"

[[redirects]]
from = "/personnes/anouck-lanot/index.html"
to = "/coop/anouck-lanot/"

[[redirects]]
from = "/projets/index.html"
to = "/films/"

