[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/personnes/alice-marsal/index.html"
to = "/coop/alice-marsal/"

[[redirects]]
from = "/personnes/romane-martin/index.html"
to = "/coop/romane-martin/"

[[redirects]]
from = "/articles/2026-04-01-publication-du-site-web/index.html"
to = "/actualites/2026-04-01-publication-du-site-web/"

[[redirects]]
from = "/personnes/clothilde-bunod/index.html"
to = "/coop/clothilde-bunod/"

[[redirects]]
from = "/coop/jean-charles-leyris/posts/index.html"
to = "/coop/jean-charles-leyris/actualites/"

[[redirects]]
from = "/agenda/2026/la-prochaine-permanence-aux-etats-generaux-du-documentaire-1/index.html"
to = "/agenda/2025/la-prochaine-permanence-aux-etats-generaux-du-documentaire-1/"

[[redirects]]
from = "/personnes/equipe-editoriale/index.html"
to = "/coop/equipe-editoriale/"

[[redirects]]
from = "/posts/2026-04-01-publication-du-site-web/index.html"
to = "/actualites/2026-04-01-publication-du-site-web/"

[[redirects]]
from = "/personnes/avrin-cardi/index.html"
to = "/coop/anne-cardi-avrin/"

[[redirects]]
from = "/coop/elodie-boin-zanchi/articles/index.html"
to = "/coop/elodie-boin-zanchi/actualites/"

[[redirects]]
from = "/personnes/categories/membres/index.html"
to = "/coop/categories/membres/"

[[redirects]]
from = "/posts/2026-05-20-prix-dnicole-nicole-remporte-le-prix-du-jury-a-visions-du-reel/index.html"
to = "/actualites/2026-05-20-prix-dnicole-nicole-remporte-le-prix-du-jury-a-visions-du-reel/"

[[redirects]]
from = "/personnes/sylvie-plunian/index.html"
to = "/coop/sylvie-plunian/"

[[redirects]]
from = "/actualites/thematique/la-vie-des-producteurs/index.html"
to = "/actualites/ressources/la-vie-des-producteurs/"

[[redirects]]
from = "/personnes/jean-charles-leyris/index.html"
to = "/coop/jean-charles-leyris/"

[[redirects]]
from = "/personnes/categories/ancien-membre/index.html"
to = "/coop/categories/anciens-membres/"

[[redirects]]
from = "/coop/elodie-boin-zanchi/posts/index.html"
to = "/coop/elodie-boin-zanchi/actualites/"

[[redirects]]
from = "/coop/alice-marsal/actualites-v01/index.html"
to = "/coop/alice-marsal/actualites/"

[[redirects]]
from = "/posts/2026-05-19-lauren-dallenbach-dans-doc-session/index.html"
to = "/actualites/2026-05-19-lauren-dallenbach-dans-doc-session/"

[[redirects]]
from = "/personnes/categories/membre/index.html"
to = "/coop/categories/membres/"

[[redirects]]
from = "/tenk/index.html"
to = "/organisations/tenk/"

[[redirects]]
from = "/posts/2026-05-19-sed-a-neque-non-nulla-consectetur-tincidunt/index.html"
to = "/actualites/2026-05-19-sed-a-neque-non-nulla-consectetur-tincidunt/"

[[redirects]]
from = "/personnes/chantal-tran/index.html"
to = "/coop/chantal-tran/"

[[redirects]]
from = "/coop/alice-marsal/articles/index.html"
to = "/coop/alice-marsal/actualites/"

[[redirects]]
from = "/coop/jean-charles-leyris/actualites-v01/index.html"
to = "/coop/jean-charles-leyris/actualites/"

[[redirects]]
from = "/personnes/flora-jouvencel/index.html"
to = "/coop/flora-jouvencel/"

[[redirects]]
from = "/archives-expositions/index.html"
to = "/expositions/archives-expositions/"

[[redirects]]
from = "/actualites/ressources-test/index.html"
to = "/actualites/ressources/"

[[redirects]]
from = "/actualites-v01/2026-05-20-prix-dnicole-nicole-remporte-le-prix-du-jury-a-visions-du-reel/index.html"
to = "/actualites/2026-05-20-prix-dnicole-nicole-remporte-le-prix-du-jury-a-visions-du-reel/"

[[redirects]]
from = "/articles/film-lie/index.html"
to = "/actualites/film-lie/"

[[redirects]]
from = "/personnes/categories/anciens-membres/index.html"
to = "/coop/categories/anciens-membres/"

[[redirects]]
from = "/personnes/raphaele-dumas/index.html"
to = "/coop/raphaele-dumas/"

[[redirects]]
from = "/personnes/claire-marty/index.html"
to = "/coop/claire-marty/"

[[redirects]]
from = "/films/2026-nicole-nicole-1/index.html"
to = "/films/2026-nicolenicole/"

[[redirects]]
from = "/coop/jean-charles-leyris/articles/index.html"
to = "/coop/jean-charles-leyris/actualites/"

[[redirects]]
from = "/actualites/2026-05-20-prix-du-jury-a-visions-du-reel-pour-nicole-nicole-1/index.html"
to = "/actualites/2026-05-20-prix-dnicole-nicole-remporte-le-prix-du-jury-a-visions-du-reel/"

[[redirects]]
from = "/personnes/aurelia-pfend/index.html"
to = "/coop/aurelia-pfend/"

[[redirects]]
from = "/actualites-v01/2026-05-19-sed-a-neque-non-nulla-consectetur-tincidunt/index.html"
to = "/actualites/2026-05-19-sed-a-neque-non-nulla-consectetur-tincidunt/"

[[redirects]]
from = "/projets/en-developpement/index.html"
to = "/films/statut/en-developpement/"

[[redirects]]
from = "/categories/diffuseur/index.html"
to = "/organisations/categories/diffuseur/"

[[redirects]]
from = "/articles/thematique/la-scic-1/index.html"
to = "/actualites/ressources/la-scic-1/"

[[redirects]]
from = "/articles/2026-05-19-lauren-dallenbach-dans-doc-session/index.html"
to = "/actualites/2026-05-19-lauren-dallenbach-dans-doc-session/"

[[redirects]]
from = "/actualites/thematique/paroles-de-cineastes/index.html"
to = "/actualites/ressources/paroles-de-cineastes/"

[[redirects]]
from = "/projets/en-diffusion/index.html"
to = "/films/statut/en-diffusion/"

[[redirects]]
from = "/actualites/2026-05-19-prix-du-jury-a-visions-du-reel-pour-nicole-nicole/index.html"
to = "/actualites/2026-05-19-sed-a-neque-non-nulla-consectetur-tincidunt/"

[[redirects]]
from = "/personnes/index.html"
to = "/coop/"

[[redirects]]
from = "/actualites-v01/2026-05-19-lauren-dallenbach-dans-doc-session/index.html"
to = "/actualites/2026-05-19-lauren-dallenbach-dans-doc-session/"

[[redirects]]
from = "/articles/2026-05-19-sed-a-neque-non-nulla-consectetur-tincidunt/index.html"
to = "/actualites/2026-05-19-sed-a-neque-non-nulla-consectetur-tincidunt/"

[[redirects]]
from = "/articles/index.html"
to = "/actualites/"

[[redirects]]
from = "/films/2026-les-cedres-1/index.html"
to = "/films/2026-nei/"

[[redirects]]
from = "/coop/alice-marsal/posts/index.html"
to = "/coop/alice-marsal/actualites/"

[[redirects]]
from = "/articles/2026-05-20-prix-dnicole-nicole-remporte-le-prix-du-jury-a-visions-du-reel/index.html"
to = "/actualites/2026-05-20-prix-dnicole-nicole-remporte-le-prix-du-jury-a-visions-du-reel/"

[[redirects]]
from = "/coop/avrin-cardi/index.html"
to = "/coop/anne-cardi-avrin/"

[[redirects]]
from = "/personnes/anouck-lanot/index.html"
to = "/coop/anouck-lanot/"

[[redirects]]
from = "/projets/index.html"
to = "/films/"

