[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/personnes/alice-marsal/index.html"
to = "/coop/alice-marsal/"

[[redirects]]
from = "/personnes/romane-martin/index.html"
to = "/coop/romane-martin/"

[[redirects]]
from = "/actualites/type/actualite-des-films/index.html"
to = "/actualites/type/actualites-des-films/"

[[redirects]]
from = "/personnes/clothilde-bunod/index.html"
to = "/coop/clothilde-bunod/"

[[redirects]]
from = "/personnes/equipe-editoriale/index.html"
to = "/coop/equipe-editoriale/"

[[redirects]]
from = "/personnes/avrin-cardi/index.html"
to = "/coop/avrin-cardi/"

[[redirects]]
from = "/personnes/categories/membres/index.html"
to = "/coop/categories/membres/"

[[redirects]]
from = "/personnes/sylvie-plunian/index.html"
to = "/coop/sylvie-plunian/"

[[redirects]]
from = "/personnes/jean-charles-leyris/index.html"
to = "/coop/jean-charles-leyris/"

[[redirects]]
from = "/personnes/categories/ancien-membre/index.html"
to = "/coop/categories/anciens-membres/"

[[redirects]]
from = "/personnes/categories/membre/index.html"
to = "/coop/categories/membres/"

[[redirects]]
from = "/tenk/index.html"
to = "/organisations/tenk/"

[[redirects]]
from = "/personnes/chantal-tran/index.html"
to = "/coop/chantal-tran/"

[[redirects]]
from = "/personnes/flora-jouvencel/index.html"
to = "/coop/flora-jouvencel/"

[[redirects]]
from = "/archives-expositions/index.html"
to = "/expositions/archives-expositions/"

[[redirects]]
from = "/films/2023-une-bosse-dans-le-coeur/index.html"
to = "/films/2022-une-bosse-dans-le-coeur/"

[[redirects]]
from = "/personnes/categories/anciens-membres/index.html"
to = "/coop/categories/anciens-membres/"

[[redirects]]
from = "/personnes/raphaele-dumas/index.html"
to = "/coop/raphaele-dumas/"

[[redirects]]
from = "/films/2024-une-bosse-dans-le-coeur/index.html"
to = "/films/2022-une-bosse-dans-le-coeur/"

[[redirects]]
from = "/personnes/claire-marty/index.html"
to = "/coop/claire-marty/"

[[redirects]]
from = "/projets/2023-une-bosse-dans-le-coeur/index.html"
to = "/films/2022-une-bosse-dans-le-coeur/"

[[redirects]]
from = "/personnes/aurelia-pfend/index.html"
to = "/coop/aurelia-pfend/"

[[redirects]]
from = "/projets/en-developpement/index.html"
to = "/films/statut/en-developpement/"

[[redirects]]
from = "/categories/diffuseur/index.html"
to = "/organisations/categories/diffuseur/"

[[redirects]]
from = "/projets/en-diffusion/index.html"
to = "/films/statut/en-diffusion/"

[[redirects]]
from = "/personnes/index.html"
to = "/coop/"

[[redirects]]
from = "/personnes/anouck-lanot/index.html"
to = "/coop/anouck-lanot/"

[[redirects]]
from = "/projets/index.html"
to = "/films/"

